export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILED = "AUTH_LOGOUT_FAILED";

export const RESET_ERROR = "RESET_ERROR";
// export const ADD_PRODUCTS = "ADD_PRODUCTS";
// export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
// export const SET_PRODUCTS = "SET_PRODUCTS";
export const REQUEST_PRODUCTS_FAILED = "REQUEST_PRODUCTS_FAILED";
export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_PRODUCTS_SUCCESS";
export const REQUEST_PRODUCTS_PENDING = "REQUEST_PRODUCTS_PENDING";

export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILED = "DELETE_PRODUCTS_FAILED";

export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED";

export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
export const EDIT_PRODUCTS_FAILED = "EDIT_PRODUCTS_FAILED";

export const RESET_PRODUCTS_SUCCESS_ALERTS = "RESET_PRODUCTS_SUCCESS_ALERTS";
export const RESET_PRODUCTS_FAILED_ALERTS = "RESET_PRODUCTS_FAILED_ALERTS";
